services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  postgres_data:
